### PR TITLE
Fifo merge

### PR DESCRIPTION
**Pull request by Licenser**
Oh good grief this is big, I'm really sorry about it. A bit of the history, when I first started _ng I did add a few things to keep up compatibility w/ newer Erlang and that kind of grew and grew to more things including AAE, dialyzer updates and quite a few cherry picks.

Now the own fork was kind of Ok for me but if we want to make this usable it seems sensible to go back using 'develop' as the central branch.

The code does compile, run eunit and eqc tests w/o failure but I'm pretty sure I've messed some things up so I don't want to blindly merge this in.

EDIT:

I forgot it also switches from rebar2 to rebar3 and from git to hex dependencies.

### CODE REVIEW

**Comment by tsloughter** [comment]
Think you could summarize the important changes?

**Comment by gpad** [comment]
Is this the _official_ continuation of riak_core?

**Comment by tsloughter** [comment]
@gpad there is no "official" continuation.

**Comment by Licenser** [comment]
Sorry about the late reply, the mail swamp got me.

The most notable changes are:

* adding AAE form riak_kv.
* R19 compatibility with a special `_rand` module as there some tricky corner cases as core depends on some rather specific behaviour of the old RNG.
* making it all use hex
* Fixing dialyzer specs for R19 dialyzer (mostly missing `undefined`s)
* Some improved error reporting
* extracting chash as an own re-usable library
* adding some -callbacks that were missing
* updating the worker pool to allow both fifo and filo message handling

**Comment by cs-victor-nascimento** [comment]
Is this going to be merged? I see there is a difference between Hex version and this repo (published is 3.0.9 and last tag here is 3.0.8). It would be good to have some statement from the maintainers of this repo about the state of things. Bet365 seems to be looking to open source the maintenance of Riak and that could help us here.

Also a sample would be greatly appreciated. 

Thanks for your hard work and having this project updated :)

**Comment by Licenser** [comment]
@cs-victor-nascimento This is a PR in the repo towards itself to do some kind of preliminary review of the changes before going to merge into whatever 'canonical upstream' is going to be.

I think the main issue is that between forking _core to _core_ng and today there have been a lot of changes to _ng which makes this a horrible leviathan of a PR. 

Personally, I can't really review my own changes - given I'd not have done them if I didn't think they were right and am probably blind to my own mistakes - so to merge that we'll need someone to step up and look this over I think.

If I ever find the time (haha ...) I'll see if it's possible to carve out seperate smaller sections of that as their own PR's but I kind of doubt that'll be possible as so many things are intertwined here.

The difference hex to here was simple me forgetting to tag the new version (sorry about that) the diff .8 -> .9 was:
```diff
diff --git a/priv/riak_core.schema b/priv/riak_core.schema
index e208d3da..68800748 100644
--- a/priv/riak_core.schema
+++ b/priv/riak_core.schema
@@ -516,7 +516,7 @@ end
   "can't be a local ip",
   fun(AddrString) ->
     case inet_parse:address(AddrString) of
-      {ok, {127, _, _, _}} -> false;
+      {ok, {127, 0, _, _}} -> false;
       {ok, _} -> true;
       {error, _} -> false
     end
diff --git a/src/riak_core.app.src b/src/riak_core.app.src
index 69586d1f..e7b210ab 100644
--- a/src/riak_core.app.src
+++ b/src/riak_core.app.src
@@ -1,6 +1,6 @@
 {application,riak_core,
     [{description,"Riak Core"},
-     {vsn,"3.0.8"},
+     {vsn,"3.0.9"},
      {modules,[]},
      {registered,[]},
      {included_applications,[riak_ensemble,chash]},
```

**Pull request closed without merging**
