### PR TITLE
Erlang 21 compatibility

### PR DESCRIPTION
**Pull request by Licenser**
Support for erlang 21 without hacky overwrites or warnings.

SSL seems to still cause issues

### CODE REVIEW

**Comment by koudelka** [comment]
🙏

**Comment by Licenser** [comment]
Note this is against the riak_core_ng branch (with all it's horrors and wonders) but I suspect that those changes should be easily cherry-picked into vanilla core. I'll look into that once it's actually working ;)

**Comment by Licenser** [comment]
This should be completely working now, any feedback would be welcome before I merge and publish this would be very welcome

**Comment by getong** [comment]
My building error msg:
```
===> Compiling src/riak_core_handoff_receiver.erl failed
src/riak_core_handoff_receiver.erl:72: ssl:ssl_accept/3: deprecated; use ssl:handshake/3 instead
```

**Comment by Licenser** [comment]
Oh that must be a change in the latest RC :) thanks! I'll update this later today or tomorrow

**Comment by Licenser** [comment]
EQC tests now all pass going to merge this! thanks @getong for helping to get this out of the door :)

**Pull request merged**
